AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Bitbucket OIDC pipelines.

Parameters:
  ProviderURL:
    Type: String
  Audience:
    Type: String
  S3BucketName:
    Type: String
  RoleName:
    Type: String
    Default: bitbucket-pipelines-oidc-role

Resources:
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Ref ProviderURL
      ClientIdList: [!Ref Audience]
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e

  OIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref Audience
      Policies:
        - PolicyName: PipelineAccess
          PolicyDocument:
            Version: '2012-10-07'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListObject
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}/
                  - !Sub arn:aws:s3:::${S3BucketName/*
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"

Outputs:
  RoleArn:
    Value: !GetAtt OIDCRole.Arn
